name: ClearML Docusaurus
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        repository: ${{ github.repository_owner }}/clearml-docs
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm install --save docusaurus-gtm-plugin
    - run: npm run build
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes build folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'build'
        destination_repo: ${{ github.repository }}
        destination_folder: 'test-dir'
        destination_branch: 'main'
        commit_msg: 'test GH actions'
