name: ClearML Docusaurus
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        repository: ${{ github.repository_owner }}/clearml-docs
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build website
      run: yarn build
